insert into reviews (place_id, source_review_id, author_name, rating, review_text, review_time, status) values
  ('ChIJSample001', 'google_review_001', 'James Mitchell', 5, 'Absolutely fantastic stay! The room was spotless, the staff were incredibly welcoming, and the location could not be better. Will definitely be back.', '2026-05-10 08:30:00+00', 'pending'),
  ('ChIJSample001', 'google_review_002', 'Sophie Laurent', 4, 'Great location right in the city center. Breakfast was delicious, though check-in took a bit longer than expected. Overall a very pleasant experience.', '2026-05-11 09:15:00+00', 'pending'),
  ('ChIJSample001', 'google_review_003', 'David Park', 2, 'The room had a musty smell and the air conditioning was barely working. Service needs significant improvement. Disappointed given the price point.', '2026-05-12 14:00:00+00', 'pending'),
  ('ChIJSample001', 'google_review_004', 'Emily Carter', 5, 'A perfect experience from start to finish. The front desk team was exceptionally attentive and went out of their way to make us feel at home.', '2026-05-13 10:45:00+00', 'resolved'),
  ('ChIJSample001', 'google_review_005', 'Michael Torres', 3, 'Room was decent and the price was fair, but the Wi-Fi was unreliable and the pool was closed without any prior notice. A bit frustrating.', '2026-05-14 16:20:00+00', 'pending'),
  ('ChIJSample001', 'google_review_006', 'Anna Müller', 1, 'Booked a deluxe room but was given a standard one instead. Staff refused to address the issue or offer any compensation. Very disappointing.', '2026-05-15 11:00:00+00', 'pending'),
  ('ChIJSample001', 'google_review_007', 'Thomas Nguyen', 4, 'Elegant atmosphere with a stunning view. The in-house restaurant served some of the best food I have had on this trip. Highly recommended.', '2026-05-16 19:30:00+00', 'pending'),
  ('ChIJSample001', 'google_review_008', 'Rachel Kim', 5, 'My third stay here and I am never disappointed. The quality and consistency are remarkable — this hotel sets the gold standard for hospitality.', '2026-05-17 08:00:00+00', 'resolved'),
  ('ChIJSample001', 'google_review_009', 'Oliver Bennett', 2, 'Overpriced for what you get. The bathroom fixtures were outdated and the hot water was intermittent throughout our stay. Expected better.', '2026-05-18 13:10:00+00', 'pending'),
  ('ChIJSample001', 'google_review_010', 'Isabella Rossi', 4, 'Beautiful hotel with a professional and friendly team. Only minor complaint is that the parking area is quite cramped. Would still recommend.', '2026-05-19 17:45:00+00', 'pending');
