"use client";

import { useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from "@/components/ui/dialog";
import { cn } from "@/lib/cn";
import type { AIResponse, Tone } from "@/types";

const TONE_LABELS: Record<Tone, string> = {
  standard: "Standard",
  friendly: "Friendly",
  apologetic: "Apologetic",
};

interface AIRepliesDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  replies: AIResponse[];
}

export function AIRepliesDialog({
  open,
  onOpenChange,
  replies,
}: AIRepliesDialogProps) {
  const [selectedId, setSelectedId] = useState<string | null>(null);

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-lg">
        <DialogHeader>
          <DialogTitle>AI Reply Suggestions</DialogTitle>
          <DialogDescription>
            Select one of the 3 replies generated by AI.
          </DialogDescription>
        </DialogHeader>

        <div className="flex flex-col gap-3">
          {replies.map((reply) => (
            <button
              key={reply.id}
              type="button"
              onClick={() => setSelectedId(reply.id)}
              className={cn(
                "w-full rounded-lg border p-3 text-left text-sm transition-colors",
                selectedId === reply.id
                  ? "border-primary bg-primary/5"
                  : "border-border hover:bg-muted"
              )}
            >
              <span className="mb-1 block text-xs font-medium uppercase tracking-wide text-muted-foreground">
                {TONE_LABELS[reply.tone]}
              </span>
              <p className="leading-relaxed">{reply.content}</p>
            </button>
          ))}
        </div>
      </DialogContent>
    </Dialog>
  );
}
